#   This is the default config for Lukkit 2.0 and above.

# Leave this line alone please, I'm begging you, just don't change it!
cfg-version: 3

# Enable the debug globals for the Lua compiler
lua-debug: false

# Should I check for updates and let you know?
update-checker: true

# Whether or not /lukkit run can be used.
can-run-code: true
